/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.c_customerAdmin;
import java.awt.event.ActionListener;
import javax.swing.JInternalFrame;
import model.m_customerAdmin;

/**
 *
 * @author L
 */
public class v_menuDeptCol extends javax.swing.JFrame {

    /**
     * Creates new form v_menuDeptCol
     */
    public v_menuDeptCol() {
        initComponents();
        setUndecorated(true);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setVisible(true);
    }

    public void LogoutButton(ActionListener a) {
        logoutbtn.addActionListener(a);
    }

    public void PembayaranButton(ActionListener a) {
        pembayaranBtn.addActionListener(a);
    }

    public void AngsuranButton(ActionListener a) {
        angsuranBtn.addActionListener(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new usu.widget.Panel();
        toolBarStyle1 = new usu.widget.glass.ToolBarStyle();
        label1 = new usu.widget.Label();
        pembayaranBtn = new usu.widget.ButtonGlass();
        label2 = new usu.widget.Label();
        angsuranBtn = new usu.widget.ButtonGlass();
        label3 = new usu.widget.Label();
        logoutbtn = new usu.widget.ButtonGlass();
        label4 = new usu.widget.Label();
        label5 = new usu.widget.Label();
        label6 = new usu.widget.Label();
        label7 = new usu.widget.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1368, 768));

        panel1.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/gambar/blurry_blue_background-wallpaper-1366x768.jpg"))); // NOI18N

        toolBarStyle1.setRollover(true);

        label1.setForeground(new java.awt.Color(77, 77, 77));
        label1.setText("--------------------------------------");
        toolBarStyle1.add(label1);

        pembayaranBtn.setForeground(new java.awt.Color(255, 255, 255));
        pembayaranBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/billICO.png"))); // NOI18N
        pembayaranBtn.setText("PEMBAYARAN");
        pembayaranBtn.setFocusable(false);
        pembayaranBtn.setFont(new java.awt.Font("Roboto Lt", 1, 11)); // NOI18N
        pembayaranBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pembayaranBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBarStyle1.add(pembayaranBtn);

        label2.setForeground(new java.awt.Color(77, 77, 77));
        label2.setText("--------------------------------------");
        toolBarStyle1.add(label2);

        angsuranBtn.setForeground(new java.awt.Color(255, 255, 255));
        angsuranBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/angsuranICO.png"))); // NOI18N
        angsuranBtn.setText("ANGSURAN");
        angsuranBtn.setFocusable(false);
        angsuranBtn.setFont(new java.awt.Font("Roboto Lt", 1, 11)); // NOI18N
        angsuranBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        angsuranBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBarStyle1.add(angsuranBtn);

        label3.setForeground(new java.awt.Color(77, 77, 77));
        label3.setText("--------------------------------------");
        toolBarStyle1.add(label3);

        logoutbtn.setForeground(new java.awt.Color(255, 0, 0));
        logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logoutICO.png"))); // NOI18N
        logoutbtn.setText("LOGOUT");
        logoutbtn.setFocusable(false);
        logoutbtn.setFont(new java.awt.Font("Roboto Lt", 1, 11)); // NOI18N
        logoutbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoutbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBarStyle1.add(logoutbtn);

        label4.setForeground(new java.awt.Color(77, 77, 77));
        label4.setText("--------------------------------------");
        toolBarStyle1.add(label4);

        label5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/debtcoll.png"))); // NOI18N

        label6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/adiraLogo.png"))); // NOI18N

        label7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/KATA.png"))); // NOI18N

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(toolBarStyle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(toolBarStyle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );

        getContentPane().add(panel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1384, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_menuDeptCol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_menuDeptCol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_menuDeptCol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_menuDeptCol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_menuDeptCol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.widget.ButtonGlass angsuranBtn;
    private usu.widget.Label label1;
    private usu.widget.Label label2;
    private usu.widget.Label label3;
    private usu.widget.Label label4;
    private usu.widget.Label label5;
    private usu.widget.Label label6;
    private usu.widget.Label label7;
    private usu.widget.ButtonGlass logoutbtn;
    private usu.widget.Panel panel1;
    private usu.widget.ButtonGlass pembayaranBtn;
    private usu.widget.glass.ToolBarStyle toolBarStyle1;
    // End of variables declaration//GEN-END:variables
}
