/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import controller.c_customerAdmin;
import java.awt.event.ActionListener;
import javax.swing.JInternalFrame;

/**
 *
 * @author cubo69
 */
public class v_menuManager extends javax.swing.JFrame {

    /**
     * Creates new form v_menuUser
     */
    public v_menuManager() {
        initComponents();
        setUndecorated(true);
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    
    public void CustomerButton(ActionListener a) {
        custBtn.addActionListener(a);
    }
    public void PenjualanButton(ActionListener a) {
        penjualanBtn.addActionListener(a);
    }
    public void KreditanButton(ActionListener a) {
        kreditanBtn.addActionListener(a);
    }
    public void logoutButton(ActionListener a) {
        logoutBtn.addActionListener(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new usu.widget.Panel();
        toolBarStyle1 = new usu.widget.glass.ToolBarStyle();
        label1 = new usu.widget.Label();
        custBtn = new usu.widget.ButtonGlass();
        label2 = new usu.widget.Label();
        penjualanBtn = new usu.widget.ButtonGlass();
        label3 = new usu.widget.Label();
        kreditanBtn = new usu.widget.ButtonGlass();
        label4 = new usu.widget.Label();
        logoutBtn = new usu.widget.ButtonGlass();
        label5 = new usu.widget.Label();
        label6 = new usu.widget.Label();
        label7 = new usu.widget.Label();
        label8 = new usu.widget.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1368, 768));

        panel1.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/gambar/blurry_blue_background-wallpaper-1366x768.jpg"))); // NOI18N

        toolBarStyle1.setRollover(true);
        toolBarStyle1.setPreferredSize(new java.awt.Dimension(1290, 194));

        label1.setForeground(new java.awt.Color(77, 77, 77));
        label1.setText("-------------------");
        toolBarStyle1.add(label1);

        custBtn.setForeground(new java.awt.Color(255, 255, 255));
        custBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/custICO_1.png"))); // NOI18N
        custBtn.setText("CUSTOMER");
        custBtn.setFocusable(false);
        custBtn.setFont(new java.awt.Font("Roboto Lt", 1, 11)); // NOI18N
        custBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        custBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        custBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custBtnActionPerformed(evt);
            }
        });
        toolBarStyle1.add(custBtn);

        label2.setForeground(new java.awt.Color(77, 77, 77));
        label2.setText("--------------------------------------");
        toolBarStyle1.add(label2);

        penjualanBtn.setForeground(new java.awt.Color(255, 255, 255));
        penjualanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/salesICO.png"))); // NOI18N
        penjualanBtn.setText("PENJUALAN");
        penjualanBtn.setFocusable(false);
        penjualanBtn.setFont(new java.awt.Font("Roboto Lt", 1, 11)); // NOI18N
        penjualanBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        penjualanBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        penjualanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjualanBtnActionPerformed(evt);
            }
        });
        toolBarStyle1.add(penjualanBtn);

        label3.setForeground(new java.awt.Color(77, 77, 77));
        label3.setText("--------------------------------------");
        toolBarStyle1.add(label3);

        kreditanBtn.setForeground(new java.awt.Color(255, 255, 255));
        kreditanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kreditanICO.png"))); // NOI18N
        kreditanBtn.setText("PRODUK KREDIT");
        kreditanBtn.setFocusable(false);
        kreditanBtn.setFont(new java.awt.Font("Roboto Lt", 1, 11)); // NOI18N
        kreditanBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kreditanBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kreditanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kreditanBtnActionPerformed(evt);
            }
        });
        toolBarStyle1.add(kreditanBtn);

        label4.setForeground(new java.awt.Color(77, 77, 77));
        label4.setText("--------------------------------------");
        toolBarStyle1.add(label4);

        logoutBtn.setForeground(new java.awt.Color(255, 0, 0));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logoutICO.png"))); // NOI18N
        logoutBtn.setText("LOGOUT");
        logoutBtn.setFocusable(false);
        logoutBtn.setFont(new java.awt.Font("Roboto Lt", 1, 11)); // NOI18N
        logoutBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoutBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBarStyle1.add(logoutBtn);

        label5.setForeground(new java.awt.Color(77, 77, 77));
        label5.setText("-------------------");
        toolBarStyle1.add(label5);

        label6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/managerLogo.png"))); // NOI18N

        label7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/adiraLogo.png"))); // NOI18N

        label8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/KATA.png"))); // NOI18N

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(toolBarStyle1, javax.swing.GroupLayout.PREFERRED_SIZE, 1226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(85, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(toolBarStyle1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        getContentPane().add(panel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1384, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void custBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custBtnActionPerformed

    private void penjualanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjualanBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penjualanBtnActionPerformed

    private void kreditanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kreditanBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kreditanBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_menuManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_menuManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_menuManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_menuManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_menuManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.widget.ButtonGlass custBtn;
    private usu.widget.ButtonGlass kreditanBtn;
    private usu.widget.Label label1;
    private usu.widget.Label label2;
    private usu.widget.Label label3;
    private usu.widget.Label label4;
    private usu.widget.Label label5;
    private usu.widget.Label label6;
    private usu.widget.Label label7;
    private usu.widget.Label label8;
    private usu.widget.ButtonGlass logoutBtn;
    private usu.widget.Panel panel1;
    private usu.widget.ButtonGlass penjualanBtn;
    private usu.widget.glass.ToolBarStyle toolBarStyle1;
    // End of variables declaration//GEN-END:variables
}
